# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Female'), (2, 'Male')])),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'user_hack',
            },
        ),
    ]
